### ISSUE TITLE
Error while installing the container in ubuntu - Error : FNRCG0014E: GCD_DATABASE_UNAVAILABLE:

### ISSUE THREAD

**Issue by deep2297** [ibm-ecm/container-demo#21] opened 2021-07-27 09:55 UTC
Hi All,

I am getting error while installing the container in Ubuntu 20.4. Error comes while creating P8Domain:

Create P8 Domain P8Domain
[Perf Log] No interval found. Auditor disabled.
Exception in thread "main" com.filenet.api.exception.EngineRuntimeException: FNRCG0014E: GCD_DATABASE_UNAVAILABLE: The GCD database is currently not available. A file-based, read-only image of the GCD will be used in its place. All update operations will be disallowed until database availability has been restored. errorStack={
        at com.filenet.engine.persist.PersisterBase.getInstance(PersisterBase.java:179)
        at com.filenet.engine.persist.PersisterBase.getInstance(PersisterBase.java:127)
        at com.filenet.engine.persist.PersisterBase.getInstance(PersisterBase.java:263)
        at com.filenet.engine.jca.impl.RequestBrokerImpl.executeChanges(RequestBrokerImpl.java:1477)
        at com.filenet.engine.jca.impl.RequestBrokerImpl.executeChanges(RequestBrokerImpl.java:1359)
        at com.filenet.engine.ejb.EngineCoreBean._executeChanges(EngineCoreBean.java:411)
        at com.filenet.engine.ejb.EngineCoreBean.executeChanges(EngineCoreBean.java:385)
        at com.filenet.engine.ejb.EJSLocalStatelessEngineCore_22877cb1.executeChanges(EJSLocalStatelessEngineCore_22877cb1.java)
        at com.filenet.engine.ejb.EngineBean.executeChangesWithRetry(EngineBean.java:1018)
        at com.filenet.engine.ejb.EngineBean.executeChanges(EngineBean.java:958)
        at com.filenet.apiimpl.transport.ejbstubs.EJSLocalStatelessEngine_2e64c374.executeChanges(EJSLocalStatelessEngine_2e64c374.java)
        at com.filenet.apiimpl.transport.ejb.EnginePortLocal.executeChanges(EnginePortLocal.java:53)
        at com.filenet.apiimpl.wsi.ServiceSessionNst$2.run(ServiceSessionNst.java:1633)
        at java.security.AccessController.doPrivileged(AccessController.java:770)
        at javax.security.auth.Subject.doAs(Subject.java:570)
        at com.ibm.websphere.security.auth.WSSubject.doAs(WSSubject.java:172)
        at com.ibm.websphere.security.auth.WSSubject.doAs(WSSubject.java:138)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at com.filenet.apiimpl.util.J2EEUtilWSL.doAs(J2EEUtilWSL.java:357)
        at com.filenet.apiimpl.wsi.ServiceSessionNst.sMakeInternalEJBCall(ServiceSessionNst.java:1496)
        at com.filenet.apiimpl.wsi.ServiceSessionNst.sHandleIncomingRequest(ServiceSessionNst.java:1340)
        at com.filenet.engine.wsi.ListenerNst.service(ListenerNst.java:222)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:729)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:426)
        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:182)
        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)
        at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:56)
        at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1001)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1139)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1010)
        at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)
        at com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40.handleRequest(CacheServletWrapper40.java:83)
        at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:936)
        at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1134)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:415)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:374)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:577)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:511)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:359)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:326)
        at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:167)
        at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:75)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
        at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:822)
}
        at com.filenet.apiimpl.wsi.serialization.core.ExceptionSerialization.deserialize(ExceptionSerialization.java:196)
        at com.filenet.apiimpl.wsi.ServiceSessionNst.cDeserializeSoapFault(ServiceSessionNst.java:965)
        at com.filenet.apiimpl.wsi.ServiceSessionNst.cReqRespPath(ServiceSessionNst.java:433)
        at com.filenet.apiimpl.wsi.ServiceSessionNst.executeChanges(ServiceSessionNst.java:160)
        at com.filenet.apiimpl.util.SessionHandle.executeChanges(SessionHandle.java:112)
        at com.filenet.apiimpl.core.Session.callExecuteChanges(Session.java:185)
        at com.filenet.apiimpl.core.Session.executeChanges(Session.java:575)
        at com.filenet.apiimpl.core.Session.executeChange(Session.java:901)
        at com.filenet.apiimpl.core.IndependentlyPersistableObjectImpl.save(IndependentlyPersistableObjectImpl.java:76)
        at com.filenet.apiimpl.core.IndependentlyPersistableObjectImpl.save(IndependentlyPersistableObjectImpl.java:67)
        at com.ibm.utils.DomainUtil.createDomain(DomainUtil.java:41)
        at com.ibm.CETools.main(CETools.java:31)
Something wrong when creating P8 domain.
Check /root/cpit_data/cpe_data/logs/cpe-host1/messages.log to see if any error

Attaching the complete error log.

Thanks,
[cpit_log.log](https://github.com/ibm-ecm/container-demo/files/6884510/cpit_log.log)

**Comment by abrakhan** [comment] 2021-07-27 16:46
@deep2297 - This error is caused by a change in the default database port in Db2 v11.5.6.0.
You can use the earlier version v11.5.5.1 as a workaround: `docker pull ibmcom/db2:11.5.5.1`
This will be fixed in the next release of the Container PIT scripts.

**Closed** 2021-07-27 16:47 UTC

**Comment by deep2297** [comment] 2021-07-28 15:31
I followed your suggestion, but I got the error saying the ibmdb2:latest image is not available.

Please suggest if you could help me on this.

![IBM_DB2](https://user-images.githubusercontent.com/33194491/127351186-7adee221-a032-4b61-b6e6-d770c221ee62.JPG)
![IBM_DB2_](https://user-images.githubusercontent.com/33194491/127351190-97b73f60-c622-47f4-8ca5-95f50a6d11f0.JPG)

**Comment by abrakhan** [comment] 2021-07-28 16:16
@deep2297 - There are 2 way to resolve this error.

- Tag the downloaded Db2 container with the `latest` tag

OR

- Update the parameter `DB2_IMAGE_TAG` in the file `setProperties.sh`

E.g., 
```
# Downloaded DB2 container info
# To obtain this info run the command: sudo docker images
DB2_REGISTRY_URL=ibmcom
DB2_IMAGE_NAME=db2
DB2_IMAGE_TAG=11.5.5.1
```

In both cases you have to run the `install-scripts/cleanup.sh` script and re-launch the `cpit.sh` script.
